

cc_library(
    name = "apis",
    srcs = glob(["*.cc"]),
    hdrs = glob([ 
        "*.h"
    ]),
    deps = ["@com_github_google_glog//:glog",        "@com_github_tencent_rapidjson//:rapidjson",
    ],
    visibility = ["//visibility:public"],
)